blog/urls.py
from django.urls import path

from . import views

app_name='blogs'
urlpatterns=[
	path('', views.index, name='index'),
	path('add/', views.add_person, name='add_person'),
	path('<int:blog_id>/', views.detail, name='detail'),
	path('<int:blog_id>/add_educate/', views.add_educate, name='add_educate'),
	path('<int:blog_id>/add_experience/', views.add_experience, name='add_experience'),
	path('<int:blog_id>/add_skills/', views.add_skills, name='add_skills')
]

threeV/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Person(models.Model):
	p_full_name = models.CharField("full_name", max_length=50)
	p_information = models.TextField("Information")
	p_date_birth = models.DateTimeField("published")

class Education(models.Model):
	person = models.ForeignKey(Person, on_delete=models.CASCADE)
	e_start = models.CharField("from", max_length=4)
	e_end = models.CharField("to", max_length=7)	
	e_place = models.CharField("Place", max_length=200)

class Experience(models.Model):
	person = models.ForeignKey(Person, on_delete=models.CASCADE)
	ed_start = models.CharField("from", max_length=4)
	ed_end = models.CharField("to", max_length=7)	
	ed_place = models.CharField("Place", max_length=200)

class Skills(models.Model):
	person = models.ForeignKey(Person, on_delete=models.CASCADE)
	s_name = models.CharField("from", max_length=15)
	s_percent = models.IntegerField()

	

blog/views.py
from django.shortcuts import render

from django.http import Http404, HttpResponseRedirect

from .models import Person, Experience, Education, Skills

from django.urls import reverse

def index(request):
	all_humans = Person.objects.all()
	return render(request, 'blogs/list.html', {'list_of_person':all_humans})

def detail(request, blog_id):
	try:
		a=Person.objects.get(id=blog_id)
	except:
		raise Http404("No man!")

	ed=a.education_set.all()
	ex=a.experience_set.all()
	sk=a.skills_set.all()
	
	return render(request, 'blogs/info.html',{'information': a, 'education':ed, 'experience': ex, 'skill':sk})

def add_person(request):
	try:
		a=Person(p_full_name=request.POST['name'],p_information=request.POST['info'], p_date_birth=request.POST['birthday'])
		a.save()
	except:
		raise Http404("No man!")

	return detail(request, Person.objects.count())

def add_educate(request, blog_id):
	try:
		a=Person.objects.get(id=blog_id)
	except:
		raise Http404("No man!")

	a.education_set.create(e_start=request.POST['from'], e_end=request.POST['due'], e_place=request.POST['place'])

	return HttpResponseRedirect(reverse('blogs:detail', args=(a.id,)))

def add_experience(request, blog_id):
	try:
		a=Person.objects.get(id=blog_id)
	except:
		raise Http404("No man!")

	a.experience_set.create(ed_start=request.POST['from'], ed_end=request.POST['due'], ed_place=request.POST['place'])

	return HttpResponseRedirect(reverse('blogs:detail', args=(a.id,)))

def add_skills(request, blog_id):
	try:
		a=Person.objects.get(id=blog_id)
	except:
		raise Http404("No man!")

	a.skills_set.create(s_name=request.POST['name'], s_percent=request.POST['perc'])

	return HttpResponseRedirect(reverse('blogs:detail', args=(a.id,)))

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Chooser</title>
	<link rel="stylesheet" href="">
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>

blog/templates/blogs/info.html
{% extends 'index.html' %}

{% block full-name %}
	
	{{information.p_full_name}}

{% endblock %}

{% block information %}
	
	{{information.p_information}}

{% endblock %}

{% block educate %}

	{% for a in education %}

		<div class="fh5co-feature">
			<div class="fh5co-icon">
				<i class="icon-graduation-cap"></i>
			</div>
			<div class="fh5co-text">
				<h2>{{a.e_start}}-{{a.e_end}}</h2>
				<p>{{a.e_place}}</p>
			</div>
		</div>		
	{% endfor %}

{% endblock %}



{% block exper %}

	{% for a in experience %}

		<div class="fh5co-feature">
			<div class="fh5co-icon">
				<i class="icon-black-tie"></i>
			</div>
			<div class="fh5co-text">
				<h2>{{a.ed_start}}-{{a.ed_end}}</h2>
				<h3>{{a.ed_place}}</h3>
			</div>
		</div> 
	{% endfor %}
{% endblock %}

{% block skills %}

	{% for a in skill %}

		<div class="col-md-4 col-sm-6 col-xs-12 text-center">
			<div class="chart" data-percent="{{a.s_percent}}"><span><strong>{{a.s_name}}</strong>{{a.s_percent}}%</span></div>
		</div>
		
	{% endfor %}
{% endblock %}

blog/templates/blogs/list.html
{% extends 'reg_page.html' %}

{% block optin %}

	{% for a in list_of_person %}

		<option value="{% url 'blogs:detail' a.id %}">{{a.p_full_name}}</option>

	{% endfor %}

{% endblock %}

blog/templates/index.html
<!DOCTYPE html>
<html > 
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Personal &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />

	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'> 
	{% load static %}
	<!-- Animate.css -->
	<link rel="stylesheet" href="/static/css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="/static/css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="/static/css/bootstrap.css">
	<!-- Theme style  -->
	<link rel="stylesheet" href="/static/css/style.css">

	<!-- Modernizr JS -->
	<script src="/static/js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
	<style type="text/css" media="screen">
		.dddiii {
		  padding: 16px;
		  background-color: white;
		}

		/* Full-width input fields */
		.iiinnn[type=text], .iiinnn[type=password] {
		  width: 100%;
		  padding: 15px;
		  margin: 5px 0 22px 0;
		  display: inline-block;
		  border: none;
		  background: #000;
		}

		.iiinnn[type=text]:focus, .iiinnn[type=password]:focus {
		  background-color: rgb(0, 0, 0);
		  outline: none;
		}

		/* Overwrite default styles of hr */
		hr {
		  border: 1px solid #f1f1f1;
		  margin-bottom: 25px;
		}

		/* Set a style for the submit button */
		.bbbttt {
		  background-color: #4CAF50;
		  color: white;
		  padding: 16px 20px;
		  margin: 8px 0;
		  border: none;
		  cursor: pointer;
		  width: 100%;
		  opacity: 0.9;
		}

		.bbbttt:hover {
		  opacity: 1;
		}
	</style>

	</head>
	<body style="background-image: url(/static/images/bg_img.jpg);">
	
	<div id="fh5co-main">
		<div class="fh5co-tab-wrap">
			<ul class="fh5co-tab-menu">
				<li class="active"><a href="#" data-tab="1"><span class="icon icon-glass"></span><span class="menu-text">Profile</span></a></li>
				<li><a href="#" data-tab="2"><span class="icon icon-graduation-cap"></span><span class="menu-text">Educations</span></a></li>
				<li><a href="#" data-tab="3"><span class="icon icon-black-tie"></span><span class="menu-text">Experiences</span></a></li>
				<li><a href="#" data-tab="4" data-pie="yes"><span class="icon icon-fighter-jet"></span><span class="menu-text">Skillss</span></a></li>
			</ul>
			<div class="fh5co-tab-content active" data-content="1">
				<div class="fh5co-content-inner text-center">
					<div class="row row-bottom-padded-sm">
						<div class="col-md-12">
							<figure>
								<img src="/static/images/profile_img.png" alt="Free HTML5 Wesbite Template by FreeHTML5.co">
							</figure>
							<h1>{% block full-name %}{% endblock %}</h1>
							<p>{% block information %}{% endblock %}</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 fh5co-counter">
							<div class="fh5co-number fh5co-left">10</div>
							<div class="fh5co-text">
								<h3 class="border-bottom">Years of experience in Web Design</h3>
								<p>More information</p>
							</div>
						</div>
					</div>
					<ul class="fh5co-social">
						<li><a href="#"><i class="icon-envelope"></i></a></li>
						<li><a href="#"><i class="icon-twitter"></i></a></li>
						<li><a href="#"><i class="icon-instagram"></i></a></li>
						<li><a href="#"><i class="icon-google"></i></a></li>
						<li><a href="#"><i class="icon-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="fh5co-tab-content" data-content="2">
				<div class="fh5co-content-inner">
					<div class="row">
						<div class="col-md-12">
							<p>Far far away, behind the word mountains, far from the countries.</p>

							<!--<div class="fh5co-feature">
								<div class="fh5co-icon">
									<i class="icon-graduation-cap"></i>
								</div>
								<div class="fh5co-text">
									<h2>{% block a %}{% endblock %}</h2>
									<p>Far far away, behind the word mountains, far from the countries.</p>
								</div>
							</div>

							<div class="fh5co-feature">
								<div class="fh5co-icon">
									<i class="icon-graduation-cap"></i>
								</div>
								<div class="fh5co-text">
									<h2>2004-2008</h2>
									<p>Far far away, behind the word mountains, far from the countries.</p>
								</div>
							</div>

							<div class="fh5co-feature">
								<div class="fh5co-icon">
									<i class="icon-graduation-cap"></i>
								</div>
								<div class="fh5co-text">
									<h2>2008-2012</h2>
									<p>Far far away, behind the word mountains, far from the countries.</p>
								</div>
							</div>-->
							{% block educate %}{% endblock %}
							
						</div>
						<form action="{% url 'blogs:add_educate' information.id %}" method="POST">
						
                        {% csrf_token %}
							  <div class="dddiii">
							    <h1 style="color: black">Add Educations</h1>
							    <input class='iiinnn' type="text" placeholder="Year from..." name="from" required>
							    <input class='iiinnn' type="text" placeholder="Place" name="place" required>

							    <input class='iiinnn' type="text" placeholder="due" name="due" required>
							    <hr>
							    <button type="submit" class="bbbttt">Add</button>
							  </div>
							</form>
					</div>
				</div>
			</div>
			<div class="fh5co-tab-content" data-content="3">
				<div class="fh5co-content-inner">
					<div class="row">
						<div class="col-md-12">

							<p>I have the privilege to work with these cool companies.</p>

							<!--<div class="fh5co-feature">
								<div class="fh5co-icon">
									<i class="icon-black-tie"></i>
								</div>
								<div class="fh5co-text">
									<h2>2008 - Present</h2>
									<h3>XYZ Inc.</h3>
									<p>Far far away, behind the word mountains, far from the countries.</p>
								</div>
							</div>

							<div class="fh5co-feature">
								<div class="fh5co-icon">
									<i class="icon-black-tie"></i>
								</div>
								<div class="fh5co-text">
									<h2>2004-2008</h2>
									<h3>Previous Ltd Co.</h3>
									<p>Far far away, behind the word mountains, far from the countries.</p>
								</div>
							</div>

							<div class="fh5co-feature">
								<div class="fh5co-icon">
									<i class="icon-black-tie"></i>
								</div>
								<div class="fh5co-text">
									<h2>1999-2004</h2>
									<h3>Previous Ltd Co.</h3>
									<p>Far far away, behind the word mountains, far from the countries.</p>
								</div>
							</div>-->
							{% block exper %}{% endblock %}
						</div>
						<form action="{% url 'blogs:add_experience' information.id %}" method="POST">
						
                        {% csrf_token %}
							  <div class="dddiii">
							    <h1 style="color: black">Add Educations</h1>
							    <input class='iiinnn' type="text" placeholder="Year from..." name="from" required>
							    <input class='iiinnn' type="text" placeholder="Place" name="place" required>
							    <input class='iiinnn' type="text" placeholder="due" name="due" required>
							    <hr>
							    <button type="submit" class="bbbttt">Add</button>
							  </div>
							</form>
					</div>
				</div>
			</div>
			<div class="fh5co-tab-content" data-content="4">
				<div class="fh5co-content-inner">
					<div class="row">
						<div class="col-md-12">
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
						<!--<div class="col-md-4 col-sm-6 col-xs-12 text-center">
							<div class="chart" data-percent="95"><span><strong>HTML5</strong>95%</span></div>
						</div>
						<div class="col-md-4 col-sm-6 col-xs-12 text-center">
							<div class="chart" data-percent="93"><span><strong>CSS3</strong>93%</span></div>
						</div>
						<div class="col-md-4 col-sm-6 col-xs-12 text-center">
							<div class="chart" data-percent="90"><span><strong>jQuery</strong>90%</span></div>
						</div>

						<div class="col-md-4 col-sm-6 col-xs-12 text-center">
							<div class="chart" data-percent="89"><span><strong>PHP</strong>89%</span></div>
						</div>
						<div class="col-md-4 col-sm-6 col-xs-12 text-center">
							<div class="chart" data-percent="85"><span><strong>MySQL</strong>85%</span></div>
						</div>
						<div class="col-md-4 col-sm-6 col-xs-12 text-center">
							<div class="chart" data-percent="90"><span><strong>AngularJS</strong>90%</span></div>
						</div>
-->						{% block skills %}{% endblock %}
					</div>
					<form action="{% url 'blogs:add_skills' information.id %}" method="POST">
						
                        {% csrf_token %}
							  <div class="dddiii">
							    <h1 style="color: black">Add Educations</h1>
							    <input class='iiinnn' type="text" placeholder="Skill" name="name" required>
							    <input class='iiinnn' type="text" placeholder="Percentage" name="perc" required>
							    <hr>
							    <button type="submit" class="bbbttt">Add</button>
							  </div>
							</form>
				</div>
			</div>
		</div>
		<footer id="fh5co-footer">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center">
					<small>
						&copy; 2016 Personal Free HTML5 Template. All Rights Reserved. <span class="fh5co-author">
						Designed by <a href="http://freehtml5.co" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></span>
					</small>
				</div>
			</div>
		</footer>
	</div>
	
	<!-- jQuery -->
	<script src="/static/js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="/static/js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="/static/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="/static/js/jquery.waypoints.min.js"></script>
	<!-- Easy PieChart -->
	<script src="/static/js/jquery.easypiechart.min.js"></script>
	<!-- MAIN JS -->
	<script src="/static/js/main.js"></script>

	</body>
</html>

blog/templates/reg_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>
    {% load static %}
    <!-- Icons font CSS-->
    <link href="/static/register/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="/static/register/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="/static/register/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="/static/register/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="/static/register/css/main.css" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins" >
        <div class="wrapper wrapper--w780" >
            <div class="card card-3" style="width:1000px; height: 600px">

                <div class="card-heading"></div>
                <div class="input-group">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select name="gender" onchange="window.location.href=this.options[this.selectedIndex].value">
                                    <option disabled="disabled" selected="selected">Select profile </option>
                                    {% block optin %}{% endblock %}
                                </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                <div class="card-body">
                    <h2 class="title">Registration Info</h2>
                    <form action="{% url 'blogs:add_person' %}" method="POST">

                        {% csrf_token %}


                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Name" name="name">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Birthday" name="birthday">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" placeholder="Email" name="info">
                        </div>
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="/static/register/vendor/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="/static/register/vendor/select2/select2.min.js"></script>
    <script src="/static/register/vendor/datepicker/moment.min.js"></script>
    <script src="/static/register/vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="/static/register/js/global.js"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->